services:
  db-itineria:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user-db-itineria
      MYSQL_DATABASE: itineria_db
      MYSQL_USER: admin-user-itineria
      MYSQL_PASSWORD: llha23_gg#9Fa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_HOST: db-itineria
      DB_PORT: 3306
      DB_NAME: itineria_db
      DB_USER: admin-user-itineria
      DB_PASSWORD: llha23_gg#9Fa
      JWT_SECRET: T%&@2V#mefwyyG@QKR6e^hqzUFfZ%xgwEpehKbQV^wX^gEy3
    depends_on:
      - db-itineria

volumes:
  db_data: