name: Deploy to AWS Auto Scaling via Instance Refresh (OIDC)

on:
  push:
    branches:
      - main

# Permessi necessari per permettere a GitHub di richiedere il token OIDC ad AWS
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Scarica il codice
      - name: Checkout del codice
        uses: actions/checkout@v4

      # Autenticazione sicura su AWS tramite OIDC
      - name: Configura AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login su Amazon ECR
      - name: Login su Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      # Build e Push dell'immagine Docker
      - name: Build e Push dell'immagine su ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: travel-diary
          IMAGE_TAG: latest
        run: |
          docker build --no-cache --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Avvia il Refresh delle Istanze nell'Auto Scaling Group
      - name: Esegui Deploy via AWS Instance Refresh
        run: |
          aws ec2 start-instance-refresh \
            --auto-scaling-group-name "${{ secrets.AWS_ASG_NAME }}" \
            --preferences '{"MinHealthyPercentage": 50}'